FROM node:24-alpine AS builder
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm ci
COPY . .
ARG NEXT_PUBLIC_WS_SERVER
ARG NEXT_PUBLIC_TURNSTILE_KEY
ARG NEXT_PUBLIC_SESSION_MAX_AGE
ARG NEXT_PUBLIC_LOGLEVEL
ENV NEXT_PUBLIC_WS_SERVER=$NEXT_PUBLIC_WS_SERVER
ENV NEXT_PUBLIC_TURNSTILE_KEY=$NEXT_PUBLIC_TURNSTILE_KEY
ENV NEXT_PUBLIC_SESSION_MAX_AGE=$NEXT_PUBLIC_SESSION_MAX_AGE
ENV NEXT_PUBLIC_LOGLEVEL=$NEXT_PUBLIC_LOGLEVEL
ENV NEXT_TELEMETRY_DISABLED=1
RUN npm run build

FROM node:24-alpine as production
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/.next/standalone ./
USER node





