import type { Metadata } from "next"
import "./globals.css"

import * as cookies from "@/app/lib/cookies"
import { getProfile } from "@/app/lib/requests"
import Header from "@/app/ui/header"
import { ProfileProvider } from "@/app/providers"
import type { Profile } from "@/app/lib/interfaces"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let session = await cookies.getSession()
  let profile: Profile | undefined = undefined
  let error: string | undefined = undefined

  if ( session ) {
    let response = await getProfile(session)
    profile = response.profile
    error = response.error
  }

  return (
    <html lang="en">
      <body>
        <ProfileProvider session={session} profile={profile}>
          <Header />
          {children}
        </ProfileProvider>
      </body>
    </html>
  )
}
